name: deploy and release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install
        env:
          CI: true
        run: yarn install --immutable --immutable-cache --check-cache

      - name: test
        run: yarn run testA

      - name: lint
        run: yarn run lint

      - name: Build Storybook
        run: yarn run build-storybook

      - name: Deploy Storybook to S3 bucket
        run: aws s3 sync ./storybook-static/ s3://${{ vars.S3_BUCKET }} --delete

      - name: Invalidate CF cache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.DISTRIBUTION_ID }} --paths "/*"

  release:
    needs: deploy
    name: Publish Package / GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install
        env:
          CI: true
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build
        if: success()
        run: yarn run build
  
      - name: Semantic Release
        if: success()
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
        run: npx semantic-release

