name: Lint and test check

on:
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deps
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Lint
        run: yarn run lint

      - name: Run Tests
        run: yarn testA
